Document: carrousel
Title: Debian carrousel Manual
Author: <insert document author here>
Abstract: This manual describes what carrousel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/carrousel/carrousel.sgml.gz

Format: postscript
Files: /usr/share/doc/carrousel/carrousel.ps.gz

Format: text
Files: /usr/share/doc/carrousel/carrousel.text.gz

Format: HTML
Index: /usr/share/doc/carrousel/html/index.html
Files: /usr/share/doc/carrousel/html/*.html
